### ISSUE TITLE
Fishing minigame timeout

### ISSUE THREAD

**Issue by skybellrock** [StardewModders/mod-ideas#257]
As most know theres currently a bug in the game where you can open your journal while fishing and you can use this to stop time while waiting for a fish to pluck. I suggest either to make a bug fix to this or make a mod where time freezes or slows down while the fishing line is threwn out. This way instead

**Comment by KarBoy2314PL** [comment]
this bug has been fixed in 1.3

**Comment by Pathoschild** [comment]
The issue still happens in the latest Stardew Valley 1.3.36.

**Comment by tiakall** [comment]
Not sure when it got fixed between then and now, but this bug no longer occurs.
